config/routes.rb
Rails.application.routes.draw do


  get 'users/index'

  root 'welcomes#index', as: 'home'
  get 'welcome' => 'welcomes#index', as: 'welcome'
  devise_for :users, controllers: {registrations: "registrations"}
  # get 'categories' => 'categories#index', as: 'category'
  # get 'categories' => 'categories#index', as: 'categories'
  # get '/categories/:category_id', to:  'questions#new#'
  # get 'question' => 'myquestions#my_index' , as: 'my_question'
  # get 'question/:id/' => 'myquestions#my_show' , as: 'show_my_question'
  # delete 'question.:id/',to: 'myquestions#destroy', as: 'delete_my_question'
  # get 'questions/:id/edit', to: 'myquestions#edit', as: 'edit_my_questions'
  # get 'questions/:id/answer', to: 'questions#answer', as: 'ganswer'
  post 'questions/:id/answer', to: 'questions#answer', as: 'answer'
  patch 'myquestions/:id/edit', to: 'myquestions#update'
  get 'tags/:tag', to: 'tags#question', as: 'tag'
  get 'tags/:name/tagquestions/:id', to: 'tags#show', as: 'tag_show'
  post 'tags/:name/tagquestions/:id/answer', to: 'tags#answer', as: 'tag_answer'
  get 'users/score', to: 'users#score', as: 'score'

  # get 'round', to: 'questions#round_index', as: 'round_index'
  # get 'round/:id', to: 'questions#round', as: 'round'

  # match '/users',   to: 'users#index',   via: 'get'
  # match '/user/:id', to: 'users#show',       via: 'get'
  # get 'answer' => 'answer#index', as: 'answer'
  # resource :questions
  #
      # resources :round
  resources :questions do
    member { post :vote }
  end
  resources :tags
  resources :myquestions
  resources :rounds
  # post 'myquestions', to: 'myquestions#create'
  # resources :users, except: [:new,:create]
    # resources :categories, except: [:destroy]
# resources :categories
#       resources :questions do
#         resources :answers
#       end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :attempts, dependent: :delete_all
  has_many :users, :through => :attempts
  acts_as_taggable
  has_reputation :votes, source: :user, aggregated_by: :sum
  validates :question, presence: true, length: {minimum: 3, maximum: 300}
  validates :answer, presence: true, length: {minimum: 1, maximum: 50}
  validates :tag_list, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  respond_to :html, :js
  before_action :authenticate_user!
  require 'will_paginate/array'

  def index
    @attempt = Attempt.where(user_id: current_user.id).pluck(:question_id)
    if params[:tag]
    @question = Question.tagged_with(params[:tag])
    else
    @question = Question.order("RANDOM()")
    @question=@question.reject{|o| @attempt.any?{|a| a==o.id} }
    @question=@question.reject{|o| o.user==current_user }
    @question=@question.paginate(:page => params[:page], :per_page => 1)
    end
    @tag="question"
  end

  def show
    @question=Question.find(params[:id])
    @answer=Question.new
  end


  def answer
    @question=Question.find(params[:id])
    @answer=Question.new(response_params)
    check = compare(@question.answer.to_s.downcase, @answer.answer.to_s.downcase)
    score = 0
    if check
      score = 4
      @question.attempts.create(user_id: current_user.id,question_id: @question.id)
    else
      score = -1
    end
    user = User.find(current_user.id)
    if (user.score == nil && score == -1)
      user.update_attribute(:score, 0)
    elsif user.score == nil && score == 4
      user.update_attribute(:score, score)
    else
      user.update_attribute(:score, user.score + score)
      if user.score < 0
        user.update_attribute(:score, 0)
      end
    end
  end


def vote
  value = params[:type] == "up" ? 1 : -1
  @question = Question.find(params[:id])
  @question.add_or_update_evaluation(:votes, value, current_user)
end


  private
    def post_params
      params.require(:question).permit(:question, :answer, :tag_list)
    end
    def compare(question, answer)
      return answer == question
    end
    def response_params
      params.require(:question).permit(:question,:answer,:user_id)
    end
    def response_params2
      params.permit(:question,:answer)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.erb
<% obj.each do |question| %>
<% if user_signed_in? && current_user!=question.user%>
<div class="well row text-center">
<h3><%=question.question %></h3>
<p> Categories : <%= raw question.tag_list.map{|t| link_to t, tag_path(t)}.join(', ')%></p>
<p><%= pluralize question.reputation_for(:votes).to_i, "vote" %></p>
<hr>
<%= link_to "Answer" , question_path(question), :class => 'btn btn-default text-center'%>
<%= link_to "", vote_question_path(question, type: "up"), method: "post",:class => 'btn btn-default glyphicon glyphicon-arrow-up text-right' %>
<%= link_to "", vote_question_path(question, type: "down"), method: "post",:class => 'btn btn-default glyphicon glyphicon-arrow-down text-right' %>
</div>
<% end %>
<% end %>

app/views/questions/_questionCreator.html.erb
<% @index=0 %>
<% obj.each do |question| %>
<% if user_signed_in? && current_user==question.user%>

<div class="well">
<!-- <p class="text-left">Question <%= @index+=1 %></p> -->
      <h3><%= question.question%></h3>
      <%= link_to "Show" , show_my_question_path(question), :class => 'btn btn-default text-center'%>

</div>
<% end %>
<% end %>

app/views/questions/answer.html.erb
<% if @question.answer.downcase!=@answer.answer.downcase %>
<div class="well">
  <h2><%= @question.question %></h2>
  <p class="text-danger">Wrong Answer</p>
  <p class=""> Correct Answer is -> <%=@question.answer%></p>
  <%= link_to "Back to Questions", questions_path, :class => 'btn btn-default text-center' %>
  </div>
  <% else %>
  <div class="well">
    <h2><%= @question.question %></h2>
    <h4><%= @answer.answer %></h4>
    <p class="text-success">Correct Answer</p>
    <%= link_to "Back to Questions", questions_path, :class => 'btn btn-default text-center' %>
    </div>
<% end %>

app/views/questions/index.html.erb
<h1 class="text-center"> Triviaa </h1>
<%= render 'questions/question', obj: @question, atm:@attempt%>

app/views/questions/myindex.html.erb
<%= will_paginate @question %>
<%= render 'questions/questionCreator' , obj: @question%>
<%= will_paginate @question %>

app/views/questions/round_index.html.erb
<div class='well text-center'>
<% @question.each do |question| %>
<div class='well text-center'>
  <h2><%= question.question %></h2>
  <hr>
  <%= form_tag round_path(question),  remote: true do %>
    <div class="form-group">

      <%= text_field_tag(:answer, nil, class: "form-control", placeholder: "Answer of question", autofocus: true )%></br>
      <%= button_tag "Submit", class: 'btn btn-default text-center' %>

      </div>
</div>
<% end %>
<% end %>
</div>

app/views/questions/round_index.js.erb
$(document).ready ->
  $("#answer").on("ajax:success", (e, data, status, xhr) ->
    $("#answer").append xhr.responseText
  ).on "ajax:error", (e, xhr, status, error) ->
    $("#answer").append "<p>ERROR</p>"

app/views/questions/roundindex.html.erb
<div class='well text-center'>
<% @question.each do |question| %>
<div class='well text-center'>
  <h2><%= question.question %></h2>
  <hr>
  <%= form_tag round_path(question),  remote: true do %>
    <div class="form-group">

      <%= text_field_tag(:answer, nil, class: "form-control", placeholder: "Answer of question", autofocus: true )%></br>
      <%= button_tag "Submit", class: 'btn btn-default text-center' %>

      </div>
</div>
<% end %>
<% end %>
</div>

app/views/questions/roundindex.js.erb
$(document).ready ->
  $("#answer").on("ajax:success", (e, data, status, xhr) ->
    $("#answer").append xhr.responseText
  ).on "ajax:error", (e, xhr, status, error) ->
    $("#answer").append "<p>ERROR</p>"

app/views/questions/show.html.erb
    <div class='well'>
      <h2><%= @question.question %></h2>
      <hr>
      <%= form_for @answer, url: answer_path do |f| %>
        <%= f.hidden_field :question, value: @question.question %>
        <%= f.hidden_field :user, value: @question.user %>
        <div class="form-group">
          <%= f.label :answer, 'Enter Your Answer' %>
          <%= f.text_field :answer, class: "form-control", placeholder: "Answer of question", autofocus: true %></br>
          <%= f.submit("Submit", class: 'btn btn-default text-center') %>
          <%= link_to "Back to Questions", questions_path, :class => 'btn btn-default text-center' %>
          </div>
    </div>
<% end %>

app/views/questions/taganswer.html.erb
<% if @question.answer.downcase!=@answer.answer.downcase %>
<div class="well">
  <h2><%= @question.question %></h2>
  <p class="danger">Wrong Answer</p>
  <p class=""> Correct Answer is -> <%=@question.answer%></p>
  <%= link_to "Back to Question", tag_path(@tag), :class => 'btn btn-default text-center' %>
  </div>
  <% else %>
  <div class="well">
    <h2><%= @question.question %></h2>
    <h4><%= @answer.answer %></h4>
    <p class="">Correct Answer</p>
    <%= link_to "Back to Questions", tag_path(@tag), :class => 'btn btn-default text-center' %>
    </div>
<% end %>

app/views/questions/tagindex.html.erb
<h1 class="text-center"> Category : <%=@tag%></h1>
<%= render 'questions/questiontag', obj: @question, atm:@attempt%>

app/views/questions/tagshow.html.erb
    <div class='well'>
      <h2><%= @question.question %></h2>
      <hr>
      <%= form_for @answer, url: taganswer_path do |f| %>
        <%= f.hidden_field :question, value: @question.question %>
        <%= f.hidden_field :user, value: @question.user %>
        <div class="form-group">
          <%= f.label :answer, 'Enter Your Answer' %>
          <%= f.text_field :answer, class: "form-control", placeholder: "Answer of question", autofocus: true %></br>
          <%= f.submit("Submit", class: 'btn btn-default text-center') %>
          <%= link_to "Back to Questions", :back, :class => 'btn btn-default text-center' %>
          </div>
    </div>
<% end %>