config/routes.rb
Rails.application.routes.draw do


  get 'users/index'

  root 'welcomes#index', as: 'home'
  get 'welcome' => 'welcomes#index', as: 'welcome'
  devise_for :users, controllers: {registrations: "registrations"}
  # get 'categories' => 'categories#index', as: 'category'
  # get 'categories' => 'categories#index', as: 'categories'
  # get '/categories/:category_id', to:  'questions#new#'
  # get 'question' => 'myquestions#my_index' , as: 'my_question'
  # get 'question/:id/' => 'myquestions#my_show' , as: 'show_my_question'
  # delete 'question.:id/',to: 'myquestions#destroy', as: 'delete_my_question'
  # get 'questions/:id/edit', to: 'myquestions#edit', as: 'edit_my_questions'
  # get 'questions/:id/answer', to: 'questions#answer', as: 'ganswer'
  post 'questions/:id/answer', to: 'questions#answer', as: 'answer'
  patch 'myquestions/:id/edit', to: 'myquestions#update'
  get 'tags/:tag', to: 'tags#question', as: 'tag'
  get 'tags/:name/tagquestions/:id', to: 'tags#show', as: 'tag_show'
  post 'tags/:name/tagquestions/:id/answer', to: 'tags#answer', as: 'tag_answer'
  get 'users/score', to: 'users#score', as: 'score'

  # get 'round', to: 'questions#round_index', as: 'round_index'
  # get 'round/:id', to: 'questions#round', as: 'round'

  # match '/users',   to: 'users#index',   via: 'get'
  # match '/user/:id', to: 'users#show',       via: 'get'
  # get 'answer' => 'answer#index', as: 'answer'
  # resource :questions
  #
      # resources :round
  resources :questions do
    member { post :vote }
  end
  resources :tags
  resources :myquestions
  resources :rounds
  # post 'myquestions', to: 'myquestions#create'
  # resources :users, except: [:new,:create]
    # resources :categories, except: [:destroy]
# resources :categories
#       resources :questions do
#         resources :answers
#       end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/myquestions_controller.rb
class MyquestionsController < ApplicationController
  require 'will_paginate/array'

    def index
        @question = Question.all
        @question=@question.reject{|o| o.user!=current_user }
        @question = @question.paginate(:page => params[:page], :per_page => 5)
    end

    def show
      @question = Question.find(params[:id])
    end

    def edit
      @question = Question.find(params[:id])
    end

    def destroy
      @question=Question.find(params[:id])
      @question.destroy
      redirect_to myquestions_path
    end

    def new
        @question = Question.new
    end

    def create
        @question = Question.new(post_params)
        @question.user = current_user
        if(@question.save)
            redirect_to myquestions_path
        else
          render 'new'
        end
    end

    def update
    @question = Question.find(params[:id])
    if(@question.update(post_params))
        redirect_to myquestion_path(@question)
    else
        render 'edit'
        end
    end

    private
      def post_params
        params.require(:question).permit(:question, :answer, :tag_list)
      end

      def compare(question, answer)
        return answer == question
      end

      def response_params
        params.require(:question).permit(:question,:answer,:user_id)
      end
      
      def response_params2
        params.permit(:question,:answer)
      end
end

app/helpers/myquestions_helper.rb
module MyquestionsHelper
end

app/views/myquestions/_questionCreator.html.erb
<% @index=0 %>
<% obj.each do |question| %>
<% if user_signed_in? && current_user==question.user%>

<div class="well text-center">
<!-- <p class="text-left">Question <%= @index+=1 %></p> -->
      <h3 class="text-center"><%= question.question%></h3>
      <%= link_to "Show" , myquestion_path(question), :class => 'btn btn-default text-center'%>

</div>
<% end %>
<% end %>

app/views/myquestions/edit.html.erb
<h3 class="text-center">Edit Question</h3>
<div class="well">
<%=form_for :question,  method: :patch do |f| %>

<% if @question.errors.full_messages.any? %>
  <% @question.errors.full_messages.each do |error_message| %>
    <div class="alert alert-danger"><%= error_message %></div>
  <% end %>
<% end %>
<p>
  <%=f.label :question %><br>
  <%=f.text_field(:question, {:class => 'form-control'})%>
</p>

<p>
  <%= f.label :answer %><br>
  <%= f.text_area(:answer, {:class => 'form-control'})%>
</p>
  <p>
      <%= f.label :tag_list,"Categories (Seperated by Commas)" %><br/>
      <%= f.text_field :tag_list, class: "form-control"%>
  </p>
  <div class="inline text-center">
<p>
  <%= f.submit({:class => 'btn btn-primary text-center'})%>
</p>
</div>

<% end %>
</div>
</div>

app/views/myquestions/index.html.erb
<h3 class="text-center"> My Questions </h3>
<%= will_paginate @question, class: "text-center"%>
<%= render 'questionCreator' , obj: @question%>
<%= will_paginate @question, class: "text-center" %>

app/views/myquestions/new.html.erb
<h3 align="center">Create a question</h3>


<div class="form-group">
    <%= form_for(@question, url: myquestions_path, :method => 'post', :html => {class: "well", role: "form"}) do |f| %>
    <% if @question.errors.full_messages.any? %>
      <% @question.errors.full_messages.each do |error_message| %>
        <div class="alert alert-danger"><%= error_message %></div>
      <% end %>
    <% end %>

        <p>
          <%= f.label :question %><br/>
          <%= f.text_field :question, class: "form-control", placeholder: "Enter a Question", autofocus: true %>
      </p>
      <p>
          <%= f.label :answer %><br/>
          <%= f.text_field :answer, class: "form-control", placeholder: "Enter an Answer", autofocus: true %>
      </p>
      <p>
          <%= f.label :tag_list,"Categories (Seperated by Commas)" %><br/>
          <%= f.text_field :tag_list, class: "form-control", placeholder: "Enter Categories", autofocus: true %>
      </p>
        <div class="inline text-center">
          <p>
            <%= f.submit class: 'btn btn-primary' %>
          </p>
        </div>

    <% end %>
</div>

app/views/myquestions/show.html.erb
<div class="well text-center">
<h2>Question : <%= @question.question %> </h2>
<p><b>Answer :  </b><%= @question.answer %> </p>
<p><b>Categories :</b> <%= raw @question.tag_list.map{|t| link_to t, tag_path(t)}.join(', ')%></p>
<hr>
<%= link_to "Edit", edit_myquestion_path(@question), :class => 'btn btn-default'%>
<%= link_to "Delete", myquestion_path(@question),method: :delete,data: {confirm: "Are You Sure?"}, :class => 'btn btn-danger'%>
<%= link_to "Back" , myquestions_path, :class => 'btn btn-default text-center'%>
</div>