config/routes.rb
Rails.application.routes.draw do


  get 'users/index'

  root 'welcomes#index', as: 'home'
  get 'welcome' => 'welcomes#index', as: 'welcome'
  devise_for :users, controllers: {registrations: "registrations"}
  # get 'categories' => 'categories#index', as: 'category'
  # get 'categories' => 'categories#index', as: 'categories'
  # get '/categories/:category_id', to:  'questions#new#'
  # get 'question' => 'myquestions#my_index' , as: 'my_question'
  # get 'question/:id/' => 'myquestions#my_show' , as: 'show_my_question'
  # delete 'question.:id/',to: 'myquestions#destroy', as: 'delete_my_question'
  # get 'questions/:id/edit', to: 'myquestions#edit', as: 'edit_my_questions'
  # get 'questions/:id/answer', to: 'questions#answer', as: 'ganswer'
  post 'questions/:id/answer', to: 'questions#answer', as: 'answer'
  patch 'myquestions/:id/edit', to: 'myquestions#update'
  get 'tags/:tag', to: 'tags#question', as: 'tag'
  get 'tags/:name/tagquestions/:id', to: 'tags#show', as: 'tag_show'
  post 'tags/:name/tagquestions/:id/answer', to: 'tags#answer', as: 'tag_answer'
  get 'users/score', to: 'users#score', as: 'score'

  # get 'round', to: 'questions#round_index', as: 'round_index'
  # get 'round/:id', to: 'questions#round', as: 'round'

  # match '/users',   to: 'users#index',   via: 'get'
  # match '/user/:id', to: 'users#show',       via: 'get'
  # get 'answer' => 'answer#index', as: 'answer'
  # resource :questions
  #
      # resources :round
  resources :questions do
    member { post :vote }
  end
  resources :tags
  resources :myquestions
  resources :rounds
  # post 'myquestions', to: 'myquestions#create'
  # resources :users, except: [:new,:create]
    # resources :categories, except: [:destroy]
# resources :categories
#       resources :questions do
#         resources :answers
#       end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  def index
    @tags=ActsAsTaggableOn::Tag.all
  end

  def question
    @question = Question.tagged_with(params[:tag])
    @attempt = Attempt.where(user_id: current_user.id).pluck(:question_id)
    @question=@question.reject{|o| @attempt.any?{|a| a==o.id} }
    @question=@question.reject{|o| o.user==current_user }
    @question = @question.paginate(:page => params[:page], :per_page => 5)
    @tag=params[:tag]
    # @tagw="tag"
  end
  
  def show
    @question=Question.find(params[:id])
    @answer=Question.new
  end

  def answer
    @tag=params[:name]
    @question=Question.find(params[:id])
    @answer=Question.new(response_params)
    check = compare(@question.answer.to_s.downcase, @answer.answer.to_s.downcase)
    score = 0
    if check
      score = 4
      @question.attempts.create(user_id: current_user.id,question_id: @question.id)
    else
      score = -1
    end
    user = User.find(current_user.id)
    if (user.score == nil && score == -1)
      user.update_attribute(:score, 0)
    elsif user.score == nil && score == 4
      user.update_attribute(:score, score)
    else
      user.update_attribute(:score, user.score + score)
      if user.score < 0
        user.update_attribute(:score, 0)
      end
    end
  end

  private
      def post_params
        params.require(:question).permit(:question, :answer, :tag_list)
      end

      def compare(question, answer)
        return answer == question
      end

      def response_params
        params.require(:question).permit(:question,:answer,:user_id)
      end
      
      def response_params2
        params.permit(:question,:answer)
      end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_questiontag.html.erb
<% obj.each do |question| %>
<% if user_signed_in? && current_user!=question.user%>
<div class="well row text-center">
<h3><%=question.question %></h3>
<p> Categories : <%= raw question.tag_list.map{|t| link_to t, tag_path(t)}.join(', ')%></p>
<p><%= pluralize question.reputation_for(:votes).to_i, "vote" %></p>
<hr>
<%= link_to "Answer" , tag_show_path(@tag,question), :class => 'btn btn-default text-center'%>
<%= link_to "", vote_question_path(question, type: "up"), method: "post",:class => 'btn btn-default glyphicon glyphicon-arrow-up text-right' %>
<%= link_to "", vote_question_path(question, type: "down"), method: "post",:class => 'btn btn-default glyphicon glyphicon-arrow-down text-right' %>
</div>
<% end %>
<% end %>

app/views/tags/answer.html.erb
<% if @question.answer.downcase!=@answer.answer.downcase %>
<div class="well">
  <h2><%= @question.question %></h2>
  <p class="text-danger">Wrong Answer</p>
  <p class=""> Correct Answer is -> <%=@question.answer%></p>
  <%= link_to "Back to Question", tag_path(@tag), :class => 'btn btn-default text-center' %>
  </div>
  <% else %>
  <div class="well">
    <h2><%= @question.question %></h2>
    <h4><%= @answer.answer %></h4>
    <p class="text-success">Correct Answer</p>
    <%= link_to "Back to Questions", tag_path(@tag), :class => 'btn btn-default text-center' %>
    </div>
<% end %>

app/views/tags/index.html.erb
  <center><h3>Select a Category</h3></center>
<div id="tag_cloud" class="well">

  <% tag_cloud Question.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: "btn btn-default" %>
  <% end %>
</div>

app/views/tags/question.html.erb
<h3 class="text-center"> Category : <%=@tag%></h3>


<%= will_paginate @question, class: "text-center"%>
<%= render 'questiontag', obj: @question, atm:@attempt%>
<%= will_paginate @question, class: "text-center" %>

app/views/tags/show.html.erb
<div class='well'>
      <h2><%= @question.question %></h2>
      <hr>
      <%= form_for @answer, url: tag_answer_path do |f| %>
        <%= f.hidden_field :question, value: @question.question %>
        <%= f.hidden_field :user, value: @question.user %>
        <div class="form-group">
          <%= f.label :answer, 'Enter Your Answer' %>
          <%= f.text_field :answer, class: "form-control", placeholder: "Answer of question", autofocus: true %></br>
          <%= f.submit("Submit", class: 'btn btn-default text-center') %>
          <%= link_to "Back to Questions", :back, :class => 'btn btn-default text-center' %>
          </div>
        <% end %>
    </div>