config/routes.rb
Rails.application.routes.draw do


  get 'users/index'

  root 'welcomes#index', as: 'home'
  get 'welcome' => 'welcomes#index', as: 'welcome'
  devise_for :users, controllers: {registrations: "registrations"}
  # get 'categories' => 'categories#index', as: 'category'
  # get 'categories' => 'categories#index', as: 'categories'
  # get '/categories/:category_id', to:  'questions#new#'
  # get 'question' => 'myquestions#my_index' , as: 'my_question'
  # get 'question/:id/' => 'myquestions#my_show' , as: 'show_my_question'
  # delete 'question.:id/',to: 'myquestions#destroy', as: 'delete_my_question'
  # get 'questions/:id/edit', to: 'myquestions#edit', as: 'edit_my_questions'
  # get 'questions/:id/answer', to: 'questions#answer', as: 'ganswer'
  post 'questions/:id/answer', to: 'questions#answer', as: 'answer'
  patch 'myquestions/:id/edit', to: 'myquestions#update'
  get 'tags/:tag', to: 'tags#question', as: 'tag'
  get 'tags/:name/tagquestions/:id', to: 'tags#show', as: 'tag_show'
  post 'tags/:name/tagquestions/:id/answer', to: 'tags#answer', as: 'tag_answer'
  get 'users/score', to: 'users#score', as: 'score'

  # get 'round', to: 'questions#round_index', as: 'round_index'
  # get 'round/:id', to: 'questions#round', as: 'round'

  # match '/users',   to: 'users#index',   via: 'get'
  # match '/user/:id', to: 'users#show',       via: 'get'
  # get 'answer' => 'answer#index', as: 'answer'
  # resource :questions
  #
      # resources :round
  resources :questions do
    member { post :vote }
  end
  resources :tags
  resources :myquestions
  resources :rounds
  # post 'myquestions', to: 'myquestions#create'
  # resources :users, except: [:new,:create]
    # resources :categories, except: [:destroy]
# resources :categories
#       resources :questions do
#         resources :answers
#       end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
      <div class="text-center">
      © 2018 Copyright:
      <a href="https://github.com/sagarrajani"> Sagar Rajani </a>
      </div>
</footer>

app/views/layouts/application.html.erb
 <!DOCTYPE html>
<html>
  <head>
    <title>Triviaa</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag  'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'  %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-default navbar-expand-md navbar-dark bg-dark navbar-fixed-top ">
          <a class="navbar-brand" href="">Shadow Health Trivia</a>
          <div class="collapse navbar-collapse container-fluid" id="navbarsExampleDefault">
            <ul class="nav navbar-nav">

              <li class="nav-item"><%= link_to "Home", welcome_path%></li>
            </ul>
              <% if user_signed_in?%>
            <ul class="nav navbar-nav">
              <li class="nav-item"><%= link_to "Play Triviaa", questions_path%></li>
            </ul>
            <!-- <ul class="nav navbar-nav">
              <li class="nav-item"><%= link_to "Play Quick 10", rounds_path%></li>
            </ul> -->
            <ul class="nav navbar-nav">
              <li class=""><%= link_to "Create a Question", new_myquestion_path%></li>
            </ul>
            <ul class="nav navbar-nav">
              <li class=""><%= link_to "Categories", tags_path%></li>
            </ul>
            <ul class="nav navbar-nav">
              <li class=""><%= link_to "My Questions", myquestions_path%></li>
            </ul>
            <ul class="nav navbar-nav">
              <li class=""><%= link_to "View High Scores", score_path%></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class=""><%= link_to "Sign Out", destroy_user_session_path, :method => 'delete'%></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li class=""><%= link_to "#{current_user.name}'s Profile", edit_user_registration_path(current_user.id)%></li>
            </ul>

            <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li class=""><%= link_to "Log In / Sign Up", user_session_path%></li>
            </ul>
            <% end %>

          </div>
        </nav>
        <% if user_signed_in?%>
        <div class="inline">
        <p class="text-right"><%=current_user.name%>'s Score : <%=current_user.score%> (<%= current_user.reputation_for(:votes).to_i %>)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
       </div>
       <% end %>
        <div class="container">
    <%= yield %>
   
  </div>
  <%= render 'layouts/footer' %>
  </body>
</html>